Change#151/redirecionar para perfil ao se logar
universi-me/universi-front pull request #152
Opened 2023-10-09 15:31 UTC by 710lucas

## Related Issue

closes #151 

## Proposed Changes

Ao se logar o usuário é redirecionado à página de perfil

2023-10-10 13:19 UTC, NiiMiyo requested changes

2023-10-10 20:54 UTC, 710lucas commented on src/contexts/Auth/AuthProvider.tsx
> +            redirectAfterSignIn(profile.user.needProfile, profile.user.id);
opa, vou ajeitar aqui então, valeu

2023-10-10 21:19 UTC, 710lucas commented
Corrigi o erro ao se logar com o google

2023-10-12 18:37 UTC, NiiMiyo approved these changes

2023-10-12 18:58 UTC, merged