FEAT #343: Favoritar conteúdos
universi-me/universi-front pull request #367
Opened 2024-01-22 12:59 UTC by NiiMiyo

## Related Issue
Closes #343

2024-02-02 11:35 UTC, 710lucas requested changes
Só consigo favoritar algo se eu for admin, tentei com duas contas normais diferentes e não deu certo

2024-02-02 14:58 UTC, NiiMiyo commented
@710lucas 
> Só consigo favoritar algo se eu for admin, tentei com duas contas normais diferentes e não deu certo

Eu acabei de testar aqui e deu certo normalmente. Qual erro aparece?

2024-02-02 16:12 UTC, 710lucas commented
![image](https://github.com/universi-me/universi-front/assets/65160454/123b55d8-45b2-47a6-b626-3d53f41acb7e)

com admin funciona normal, mas como usuário eu recebo esse erro

2024-02-02 16:22 UTC, NiiMiyo commented
Pelo que estou vendo na API, essa mensagem acontece quando você não tem permissão de leitura na pasta em questão. Acredito que o que tá rolando é que você não está no mesmo grupo que a pasta.

Pode ser um ponto para rever sobre as regras de negócio de capacitação.

2024-02-02 16:26 UTC, 710lucas commented
Pior q eu to, eu verifiquei isso, criei um novo grupo, uma nova pasta, entrei nele e tentei favoritar e não foi

2024-02-02 16:29 UTC, 710lucas commented
Eu acho que eu "achei"  o problema, fiz o seguinte
Como admin: criei um grupo novo (grupo x), entrei no grupo x, criei um conteúdo me desloguei
Como usuário: me loguei como usuário normal, entrei no grupo x (isso causou um comportamento esquisito, basicamente me deu permissão de admin no grupo, eu posso criar conteúdos e grupos no grupo x), tentei favoritar o conteúdo e não deu certo, usei os privilegios q surgiram do nada, criei um grupo (grupo y), ainda como usuário, criei um conteúdo no grupo y e ai sim eu consegui favoritar ele, mas nenhum outro eu consigo

então eu acho que talvez esteja associado aos admins do grupo ou algo assim

2024-02-02 16:36 UTC, 710lucas approved these changes
Ta funcionando, vou aprovar ai a gente vê isso no back melhor dps

2024-02-02 17:37 UTC, NiiMiyo commented
Um problema realmente... peculiar, pra dizer o mínimo.

2024-02-02 21:02 UTC, 710lucas approved these changes

2024-02-06 19:50 UTC, rodrigor approved these changes

2024-02-06 19:53 UTC, merged