feat: roles de usuários no grupo
universi-me/universi-front pull request #449
Opened 2024-03-21 18:41 UTC by julio-ufpb

## Related Issue

Closes #412 #418 
## Proposed Changes

  -
  -
  -

2024-03-23 11:36 UTC, NiiMiyo requested changes

2024-03-23 11:36 UTC, NiiMiyo commented on src/pages/Group/GroupConfig/Roles/RolesPage.tsx
> +    const [columns, setColumns] = useState(null as string[] | null);
Alguns desses hooks não são usados em nenhum momento. Vale a pena dar uma analisada nisso pra remover ou usar eles onde necessário.

2024-04-05 11:32 UTC, NiiMiyo commented on src/pages/singin/SinginForm.tsx
> +  let RECAPTCHA_SITE_KEY = organizationEnv.recaptcha_site_key ?? import.meta.env.VITE_RECAPTCHA_SITE_KEY;
https://github.com/universi-me/universi-front/pull/449/commits/360b90271b6ff947c3f426d2a967b7fa9301b19a

2024-04-05 11:38 UTC, NiiMiyo commented on src/types/Roles.ts
> +    READ_WRITE_DELETE = 4,
https://github.com/universi-me/universi-front/pull/449/commits/e65a435f09ee66bf73cb1abe42d7e78e7a73d145

2024-04-05 11:39 UTC, NiiMiyo commented on src/types/Roles.ts
> +export const FeatureTypesToLabel = {
https://github.com/universi-me/universi-front/pull/449/commits/6e0f303fd244a6fe1af54687a21f31137cfdff8b

2024-04-05 11:43 UTC, NiiMiyo commented on src/pages/Group/GroupConfig/Roles/RolesLoader.ts
> +export async function RolesLoader(args: LoaderFunctionArgs) {
https://github.com/universi-me/universi-front/pull/449/commits/522426386f6a33a72b033b751e3efd904190caf8

2024-04-05 11:43 UTC, NiiMiyo commented on src/pages/Group/GroupConfig/Roles/RolesLoader.ts
> +    const auth = useContext(AuthContext);
https://github.com/universi-me/universi-front/pull/449/commits/522426386f6a33a72b033b751e3efd904190caf8

2024-04-05 11:43 UTC, NiiMiyo commented on src/pages/Group/GroupConfig/Roles/RolesLoader.ts
> +    if (auth.profile === null || organization === null) {
https://github.com/universi-me/universi-front/pull/449/commits/522426386f6a33a72b033b751e3efd904190caf8

2024-04-05 11:55 UTC, NiiMiyo commented on src/pages/Group/loader.ts
> +        canI('FEED',    Permission.READ, group, profile) == true ? UniversimeApi.Feed.getGroupPosts({groupId: group.id}) : {} as any,
https://github.com/universi-me/universi-front/pull/449/commits/ae701122d81391bbc5f7a9aa9eaebe94c24977bb

2024-04-05 12:10 UTC, NiiMiyo commented on src/pages/Group/GroupTabs/GroupTabs.tsx
> +                    { canI(t!.featureType!, Permission.READ, context?.group) &&
https://github.com/universi-me/universi-front/pull/449/commits/f72b37408826615c5215d5507d210ac88fec9260

2024-04-05 12:19 UTC, NiiMiyo commented on src/pages/Group/GroupTabs/GroupFeed/GroupFeed.tsx
> +                        canCreatePost() || canI("FEED", Permission.READ_WRITE, groupContext.group)
https://github.com/universi-me/universi-front/pull/449/commits/845fd5208117165577daee352eb68e6e9218c996

2024-04-05 12:22 UTC, NiiMiyo commented on src/contexts/Auth/AuthProvider.tsx
> +            organization,
https://github.com/universi-me/universi-front/pull/449/commits/9422b37e3352261a94575d0a5c8be661eddd0f74

2024-04-05 12:33 UTC, NiiMiyo commented on src/pages/Group/GroupTabs/GroupFeed/GroupFeedPost.tsx
> +                let canDelete = canI("FEED", Permission.READ_WRITE_DELETE, groupContext.group) || (groupContext.group.canEdit || data.author.user.ownerOfSession);
https://github.com/universi-me/universi-front/pull/449/commits/01014163e6f50a4b722b82d3b60b7ca4a9dd9af9

2024-04-12 12:36 UTC, NiiMiyo commented on src/contexts/Auth/AuthContext.tsx
> +    roles: any;
https://github.com/universi-me/universi-front/blob/669e76faf77f507e93bdb2b8ece678852e4c5f6b/src/types/Roles.tshttps://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 12:37 UTC, NiiMiyo commented on src/types/Roles.ts
> +    features?: RolesFeature[];
https://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 12:38 UTC, NiiMiyo commented on src/contexts/Auth/AuthContext.tsx
> +    roles: any;
https://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 12:38 UTC, NiiMiyo commented on src/utils/roles/rolesUtils.ts
> +  }
https://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 12:38 UTC, NiiMiyo commented on src/utils/roles/rolesUtils.ts
> +  let returnValueAsBoolean = (permission != null || permission != undefined);
https://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 12:39 UTC, NiiMiyo commented on src/services/UniversimeApi/Roles.ts
> +export function listRoles() : any {
https://github.com/universi-me/universi-front/commit/ab0765b528adab9bf96959dac0d3dc15b17c0db5

2024-04-12 12:40 UTC, NiiMiyo commented on src/pages/Group/GroupConfig/Roles/RolesPage.tsx
> +    const [columns, setColumns] = useState(null as string[] | null);
https://github.com/universi-me/universi-front/pull/449/commits/669e76faf77f507e93bdb2b8ece678852e4c5f6b

2024-04-12 13:22 UTC, NiiMiyo approved these changes

2024-04-25 19:55 UTC, 710lucas approved these changes

2024-04-26 10:24 UTC, merged